In [2]:
import torch

x = torch.tensor([3.0])
y = torch.tensor([2.0])

x+y,x*y,x/y,x**y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

In [42]:
x = torch.arange(4,dtype=torch.float32)
x[3]

tensor(3.)

In [10]:
B = torch.arange(20).reshape((4,5))
B,B.T

(tensor([[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]]),
 tensor([[ 0,  5, 10, 15],
         [ 1,  6, 11, 16],
         [ 2,  7, 12, 17],
         [ 3,  8, 13, 18],
         [ 4,  9, 14, 19]]))

In [31]:
A = torch.arange(20*2,dtype=float).reshape(2,5,4)
A.shape,A.sum()

(torch.Size([2, 5, 4]), tensor(780., dtype=torch.float64))

> 如果想对一个维度进行求和，应该怎么做呢？
> 就比如，几个图片叠加到一起，我想合并成一张图片，最简单的想法就是对应像素点处的像素值进行相加
> 不懂就看下边的例子，一看就明白

In [32]:
A_sum_axis0 = A.sum(axis=0)
A,A_sum_axis0,A_sum_axis0.shape,A.mean()

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.],
          [32., 33., 34., 35.],
          [36., 37., 38., 39.]]], dtype=torch.float64),
 tensor([[20., 22., 24., 26.],
         [28., 30., 32., 34.],
         [36., 38., 40., 42.],
         [44., 46., 48., 50.],
         [52., 54., 56., 58.]], dtype=torch.float64),
 torch.Size([5, 4]),
 tensor(19.5000, dtype=torch.float64))

axis = 0  -> 层
axis = 1  -> 行
axis = 2  -> 列

In [35]:
A.mean(axis=0),A.mean(axis=1),A.mean(axis=2)

(tensor([[10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.],
         [22., 23., 24., 25.],
         [26., 27., 28., 29.]], dtype=torch.float64),
 tensor([[ 8.,  9., 10., 11.],
         [28., 29., 30., 31.]], dtype=torch.float64),
 tensor([[ 1.5000,  5.5000,  9.5000, 13.5000, 17.5000],
         [21.5000, 25.5000, 29.5000, 33.5000, 37.5000]], dtype=torch.float64))

累加求和：

In [46]:
A = torch.arange(20,dtype=torch.float32).reshape(5,4)
A,A.cumsum(axis=0)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  6.,  8., 10.],
         [12., 15., 18., 21.],
         [24., 28., 32., 36.],
         [40., 45., 50., 55.]]))

向量的点积

In [43]:
y = torch.ones(4,dtype=torch.float32)
x,y,torch.dot(x,y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

矩阵的点积

In [48]:
A,x,A.shape,x.shape,torch.mv(A,x)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([0., 1., 2., 3.]),
 torch.Size([5, 4]),
 torch.Size([4]),
 tensor([ 14.,  38.,  62.,  86., 110.]))

范数的实现：

In [50]:
u = torch.tensor([3.0,-4.0])
torch.norm(u) # 向量二范数

tensor(5.)

In [53]:
torch.abs(u).sum() #向量一范数

tensor(7.)

In [54]:
torch.norm(torch.ones((4,9))) # 矩阵F范数

tensor(6.)