In [34]:
import torch
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [35]:
x.requires_grad_(True) # 找个地方存储x的梯度
x.grad

In [36]:
y = 2*torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

y = 2 * x * x.T
y对x的导数是
y' = 2 * 2 * x.T

In [37]:
y.backward() # 通过反向传播函数求出来y关于x每一个分量的梯度
x.grad

tensor([ 0.,  4.,  8., 12.])

In [38]:
x.grad == 4 * x #验证一波，全对 √

tensor([True, True, True, True])

In [39]:
# 默认情况下，PyTorch会累积梯度，我们需要清除之前的值
# 如果不清除，那么输出是：tensor([ 1.,  5.,  9., 13.])
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])